import type { Product } from "../types/product"

export const products: Product[] = [
  {
    id: "1",
    name: "Canon Camera EOS 2000, Black 10x zoom",
    price: 998.0,
    originalPrice: 1128.0,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.5,
    reviews: 154,
    orders: 154,
    category: "Electronics",
    brand: "Canon",
    features: ["10x zoom", "Black", "Professional"],
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    inStock: true,
    freeShipping: true,
    discount: 25,
  },
  {
    id: "2",
    name: "GoPro HERO6 4K Action Camera - Black",
    price: 998.0,
    originalPrice: 1128.0,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.5,
    reviews: 154,
    orders: 154,
    category: "Electronics",
    brand: "GoPro",
    features: ["4K", "Waterproof", "Action"],
    description:
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    inStock: true,
    freeShipping: true,
    discount: 15,
  },
  {
    id: "3",
    name: "Smart Watch Apple Series 7",
    price: 998.0,
    originalPrice: 1128.0,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.5,
    reviews: 154,
    orders: 154,
    category: "Electronics",
    brand: "Apple",
    features: ["Smart", "Fitness", "GPS"],
    description: "Advanced health monitoring and fitness tracking capabilities.",
    inStock: true,
    freeShipping: true,
    discount: 40,
  },
  {
    id: "4",
    name: "Gaming Headphones Pro",
    price: 998.0,
    originalPrice: 1128.0,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.5,
    reviews: 154,
    orders: 154,
    category: "Electronics",
    brand: "Sony",
    features: ["Gaming", "Noise Cancelling", "RGB"],
    description: "Professional gaming headphones with surround sound.",
    inStock: true,
    freeShipping: true,
    discount: 25,
  },
  {
    id: "5",
    name: "Mens Long Sleeve T-shirt Cotton Base Layer Slim Muscle",
    price: 98.0,
    originalPrice: 128.0,
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.2,
    reviews: 32,
    orders: 154,
    category: "Clothing",
    brand: "Fashion Brand",
    features: ["Cotton", "Slim Fit", "Long Sleeve"],
    description: "Premium cotton t-shirt with slim muscle fit design.",
    inStock: true,
    freeShipping: true,
    discount: 20,
  },
]

export const categories = ["Mobile accessory", "Electronics", "Smartphones", "Modern tech", "Clothing", "Home & Garden"]

export const brands = ["Samsung", "Apple", "Huawei", "Pocco", "Lenovo", "Canon", "GoPro", "Sony"]

export const features = [
  "Metallic",
  "Plastic cover",
  "8GB Ram",
  "Super power",
  "Large Memory",
  "4K",
  "Waterproof",
  "Gaming",
]
